#!/usr/bin/env python3
"""
REVUEX Report Generator v2.1 - Production Ready
Optimized for the 19-Scanner REVUEX Suite
"""

import json
import html
import logging
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Union

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class ReportGenerator:
    """Generate professional HTML reports with comprehensive security analysis"""

    def __init__(self, workspace: Union[str, Path]):
        self.workspace = Path(workspace)
        self.workspace.mkdir(parents=True, exist_ok=True)

        self.severity_matrix = {
            'critical': {'score': 9.5, 'color': '#d32f2f', 'icon': '🔴', 'priority': 'IMMEDIATE'},
            'high': {'score': 7.5, 'color': '#f57c00', 'icon': '🟠', 'priority': 'URGENT'},
            'medium': {'score': 5.0, 'color': '#fbc02d', 'icon': '🟡', 'priority': 'MODERATE'},
            'low': {'score': 2.0, 'color': '#388e3c', 'icon': '🟢', 'priority': 'LOW'}
        }

    def generate_html_report(self, data: Dict[str, Any], custom_sections: List[str] = None) -> Path:
        """Main entry point for generating the HTML report"""
        logger.info(f"Generating report for: {data.get('target')}")
        
        exec_summary = self._generate_executive_summary_data(data)
        
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>REVUEX Security Assessment - {data.get('target')}</title>
    <style>{self._get_enhanced_css()}</style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>REVUEX Security Assessment Report</h1>
            <p>Target: <strong>{data.get('target')}</strong> | Date: {datetime.now().strftime('%Y-%m-%d')}</p>
        </div>

        <div class="summary-grid">
            <div class="summary-card" style="border-top: 5px solid {exec_summary['risk_color']}">
                <h3>Overall Risk Score</h3>
                <div class="number" style="color: {exec_summary['risk_color']}">{exec_summary['risk_score']}/100</div>
                <p>Status: <strong>{exec_summary['risk_level']}</strong></p>
            </div>
            <div class="summary-card">
                <h3>Vulnerabilities Found</h3>
                <div class="number">{exec_summary['total_vulnerabilities']}</div>
                <p>Confirmed Exploits: {exec_summary['confirmed_exploits']}</p>
            </div>
        </div>

        <div class="section">
            <h2 class="section-title">📊 Executive Summary</h2>
            <p>This report details the security posture of <strong>{data.get('target')}</strong>. The assessment identified {exec_summary['total_vulnerabilities']} vulnerabilities.</p>
            <div class="impact-box">
                <strong>Business Impact:</strong> {exec_summary['business_impact']}<br>
                <strong>Remediation Timeline:</strong> {exec_summary['remediation_timeline']}
            </div>
        </div>

        <div class="section">
            <h2 class="section-title">🛡️ Vulnerability Findings</h2>
            {self._render_findings(data.get('vulnerabilities', []))}
        </div>

        <div class="section">
            <h2 class="section-title">🔍 Reconnaissance Data</h2>
            <div class="recon-grid">
                <div><strong>Subdomains Found:</strong> {len(data.get('reconnaissance', {}).get('subdomains', []))}</div>
                <div><strong>Tech Stack:</strong> {", ".join(self._identify_vulnerable_technologies(data))}</div>
            </div>
        </div>

        {''.join(custom_sections) if custom_sections else ''}

        <div class="footer">
            <p>Generated by REVUEX Vul Suite v2.1 | Confidential Security Document</p>
        </div>
    </div>
</body>
</html>"""

        output_file = self.workspace / "REVUEX_SECURITY_REPORT.html"
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return output_file

    def _generate_executive_summary_data(self, data: Dict) -> Dict:
        # Improved Risk Calculation Logic
        stats = data.get('statistics', {}).get('findings', {})
        vulns = data.get('vulnerabilities', [])
        
        risk_score = min(100, (
            stats.get('critical', 0) * 30 +
            stats.get('high', 0) * 15 +
            stats.get('medium', 0) * 5
        ))
        
        if risk_score > 70: level, color = 'CRITICAL', '#d32f2f'
        elif risk_score > 40: level, color = 'HIGH', '#f57c00'
        elif risk_score > 15: level, color = 'MEDIUM', '#fbc02d'
        else: level, color = 'LOW', '#388e3c'

        return {
            'risk_score': risk_score,
            'risk_level': level,
            'risk_color': color,
            'total_vulnerabilities': len(vulns),
            'confirmed_exploits': len(data.get('confirmed_bugs', [])),
            'business_impact': self._calculate_business_impact(vulns),
            'remediation_timeline': "Immediate" if risk_score > 40 else "30 Days"
        }

    def _calculate_business_impact(self, vulns: List) -> str:
        if not vulns: return "No significant risks identified."
        severities = [v.get('severity', '').lower() for v in vulns]
        if 'critical' in severities: return "High Risk: Potential for full data breach or RCE."
        if 'high' in severities: return "Elevated Risk: Unauthorized access to sensitive modules likely."
        return "Moderate: Localized impacts to specific components."

    def _render_findings(self, findings: List) -> str:
        if not findings: return "<p>No vulnerabilities found.</p>"
        html_out = ""
        for f in findings:
            sev = f.get('severity', 'low').lower()
            color = self.severity_matrix.get(sev, {}).get('color', '#333')
            html_out += f"""
            <div class="finding-card">
                <span class="severity-badge" style="background:{color}">{sev.upper()}</span>
                <h3 style="display:inline; margin-left:10px;">{html.escape(f.get('type', 'Unknown Issue'))}</h3>
                <p><strong>Endpoint:</strong> <code>{html.escape(str(f.get('url', 'N/A')))}</code></p>
                <p>{html.escape(f.get('description', 'No description provided.'))}</p>
                <div class="code-block">{html.escape(f.get('evidence', 'No evidence captured'))}</div>
            </div>"""
        return html_out

    def _identify_vulnerable_technologies(self, data: Dict) -> List:
        techs = data.get('reconnaissance', {}).get('technologies', {})
        # Flatten dictionary or list if nested
        if isinstance(techs, dict):
            return list(techs.keys())
        return ["Not Detected"]

    def _get_enhanced_css(self) -> str:
        return """
        body { font-family: 'Inter', -apple-system, sans-serif; background: #f4f7f9; color: #2c3e50; line-height: 1.6; }
        .container { max-width: 1100px; margin: 40px auto; background: white; box-shadow: 0 10px 30px rgba(0,0,0,0.05); border-radius: 12px; }
        .header { background: #1a202c; color: white; padding: 50px 30px; border-radius: 12px 12px 0 0; text-align: center; }
        .section { padding: 40px 50px; border-bottom: 1px solid #edf2f7; }
        .section-title { font-size: 1.5rem; color: #1a202c; border-left: 5px solid #3182ce; padding-left: 15px; margin-bottom: 25px; }
        .summary-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; padding: 20px 50px; margin-top: -30px; }
        .summary-card { background: white; padding: 25px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); text-align: center; }
        .number { font-size: 2.5rem; font-weight: 800; margin: 10px 0; }
        .finding-card { background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 20px; }
        .severity-badge { color: white; padding: 4px 12px; border-radius: 20px; font-size: 0.75rem; font-weight: 700; }
        .code-block { background: #1a202c; color: #a3b1bc; padding: 15px; border-radius: 6px; font-family: 'Fira Code', monospace; font-size: 0.9rem; margin-top: 10px; overflow-x: auto; }
        .impact-box { background: #ebf8ff; border-left: 4px solid #3182ce; padding: 15px; margin-top: 15px; font-size: 0.95rem; }
        .footer { padding: 30px; text-align: center; font-size: 0.85rem; color: #718096; }
        """
